version: "3"
services:
  node1:
    # image: deadly-bird
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: "http://localhost:8000"
    restart: always
    volumes:
      - database:/app/data
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DOCKER=1
      - HOST_URL=http://localhost:8000/
      - REMOTE_AUTH_USERNAME=username
      - REMOTE_AUTH_PASSWORD=password
  node2:
    # image: deadly-bird
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: "http://localhost:8001"
    restart: always
    volumes:
      - database2:/app/data
    ports:
      - 8001:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DOCKER=1
      - HOST_URL=http://localhost:8001/
      - COOKIE_NAME=sessionid2
      - REMOTE_AUTH_USERNAME=username
      - REMOTE_AUTH_PASSWORD=password
volumes:
  database:
  database2: