version: "3"
services:
  node1:
    image: deadly-bird
    restart: always
    volumes:
      - database:/app/data
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DOCKER=1
      - HOST_URL=http://localhost:8000
      - REMOTE_AUTH_USERNAME=username
      - REMOTE_AUTH_PASSWORD=password
      - STRIPE_API_KEY=sk_test_51OIZXzLmClgbbAeLhE6c2Ji2YmVtNSSGWq91H8xBDl7BKGwKz5QaeutsBEXWtL495ysuRBXDHypPiBQvzGyPo5Hb00RIPGJiOU
      - STRIPE_WEBHOOK_SECRET=whsec_de88a28a300dc10babbabcba90a581bc23d5cb8d0b34b1c6122239a6132f87e8
      - STRIPE_MONTHLY_PRICE_ID=price_1P2fzcLmClgbbAeLjS9LdyXx
      - STRIPE_YEARLY_PRICE_ID=price_1P2oY2LmClgbbAeL92dGotVx
  node2:
    image: deadly-bird
    restart: always
    volumes:
      - database2:/app/data
    ports:
      - 8001:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DOCKER=1
      - HOST_URL=http://localhost:8001
      - COOKIE_NAME=sessionid2
      - REMOTE_AUTH_USERNAME=username
      - REMOTE_AUTH_PASSWORD=password
      - STRIPE_API_KEY=sk_test_51OIZXzLmClgbbAeLhE6c2Ji2YmVtNSSGWq91H8xBDl7BKGwKz5QaeutsBEXWtL495ysuRBXDHypPiBQvzGyPo5Hb00RIPGJiOU
      - STRIPE_WEBHOOK_SECRET=?
      - STRIPE_MONTHLY_PRICE_ID=price_1P2fzcLmClgbbAeLjS9LdyXx
      - STRIPE_YEARLY_PRICE_ID=price_1P2oY2LmClgbbAeL92dGotVx

  node3:
    image: deadly-bird
    restart: always
    volumes:
      - database3:/app/data
    ports:
      - 8002:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DOCKER=1
      - HOST_URL=http://localhost:8002
      - COOKIE_NAME=sessionid3
      - REMOTE_AUTH_USERNAME=username
      - REMOTE_AUTH_PASSWORD=password
      - STRIPE_API_KEY=sk_test_51OIZXzLmClgbbAeLhE6c2Ji2YmVtNSSGWq91H8xBDl7BKGwKz5QaeutsBEXWtL495ysuRBXDHypPiBQvzGyPo5Hb00RIPGJiOU
      - STRIPE_WEBHOOK_SECRET=?
      - STRIPE_MONTHLY_PRICE_ID=price_1P2fzcLmClgbbAeLjS9LdyXx
      - STRIPE_YEARLY_PRICE_ID=price_1P2oY2LmClgbbAeL92dGotVx

volumes:
  database:
  database2:
  database3: