name: Heroku Deploy
on:
  push:
    branches:
      - dev

concurrency:
  group: heroku
  cancel-in-progress: false

jobs:
  build:
    runs-on: [self-hosted]
    environment:
      name: heroku

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Heroku Deployment
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "thedeadlybird"
          heroku_email: "wqi3@ualberta.ca"
          stack: "container"
          usedocker: true
          docker_build_args: |
            LIVE_HOST_URL
        env:
          LIVE_HOST_URL: https://thedeadlybird-123769211974.herokuapp.com/