name: Heroku Deploy
on:
  push:
    branches:
      - dev

concurrency:
  group: heroku2
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: heroku

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Heroku Deployment
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "thedeadlybird"
          heroku_email: "wqi3@ualberta.ca"
          stack: "container"
          usedocker: true
          docker_build_args: |
            LIVE_HOST_URL
            AUTH_USERNAME
            AUTH_PASSWORD
            GITHUB_API_TOKEN
            STRIPE_API_KEY
            STRIPE_WEBHOOK_SECRET
            STRIPE_MONTHLY_PRICE_ID
            STRIPE_YEARLY_PRICE_ID
        env:
          LIVE_HOST_URL: https://thedeadlybird-123769211974.herokuapp.com/
          AUTH_USERNAME: ${{secrets.REMOTE_AUTH_USERNAME}}
          AUTH_PASSWORD: ${{secrets.REMOTE_AUTH_PASSWORD}}
          GITHUB_API_TOKEN: ${{secrets.API_GITHUB_TOKEN}}
          STRIPE_API_KEY: ${{secrets.STRIPE_API_KEY}}
          STRIPE_WEBHOOK_SECRET: ${{secrets.STRIPE_WEBHOOK_SECRET_TEST}}
          STRIPE_MONTHLY_PRICE_ID: ${{vars.STRIPE_MONTHLY_PRICE_ID}}
          STRIPE_YEARLY_PRICE_ID: ${{vars.STRIPE_YEARLY_PRICE_ID}}

      - name: Heroku Deployment
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "deadly-bird-justin"
          heroku_email: "wqi3@ualberta.ca"
          stack: "container"
          usedocker: true
          docker_build_args: |
            LIVE_HOST_URL
            AUTH_USERNAME
            AUTH_PASSWORD
            GITHUB_API_TOKEN
            STRIPE_API_KEY
            STRIPE_WEBHOOK_SECRET
            STRIPE_MONTHLY_PRICE_ID
            STRIPE_YEARLY_PRICE_ID
        env:
          LIVE_HOST_URL: https://deadly-bird-justin-ce5a27ea0b51.herokuapp.com/
          AUTH_USERNAME: ${{secrets.REMOTE_AUTH_USERNAME}}
          AUTH_PASSWORD: ${{secrets.REMOTE_AUTH_PASSWORD}}
          GITHUB_API_TOKEN: ${{secrets.API_GITHUB_TOKEN}}
          STRIPE_API_KEY: ${{secrets.STRIPE_API_KEY}}
          STRIPE_WEBHOOK_SECRET: ${{secrets.STRIPE_WEBHOOK_SECRET_JUSTIN}}
          STRIPE_MONTHLY_PRICE_ID: ${{vars.STRIPE_MONTHLY_PRICE_ID}}
          STRIPE_YEARLY_PRICE_ID: ${{vars.STRIPE_YEARLY_PRICE_ID}}