name: Heroku Deploy
on:
  push:
    branches:
      - dev

concurrency:
  group: heroku
  cancel-in-progress: false

jobs:
  build:
    runs-on: [self-hosted]
    environment:
      name: heroku

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Heroku Deployment
        run: |
          heroku container:login
          heroku container:push web -a thedeadlybird
          heroku container:release web -a thedeadlybird